services:
  server:
    build: .
    container_name: server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
    volumes:
      - ./src:/server/src
      - /server/node_modules
    networks:
      - backend
    restart: always

  db:
    build: ./postgres_db
    container_name: db
    ports:
      - "5431:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge